### ISSUE TITLE
verifyDeploymentCompletion log locations and file extension

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-aws-cloudformation#118]
## Do you already have an issue opened with F5 support?
No

## Description
verifyDeploymentCompletion logs to

- /var/log/cloud/aws/verifyDeploymentCompletion.js
- /var/log/cloudlibs/verifyDeploymentCompletion.log
- /var/log/cloud/aws/install.log

Not sure if log file in /var/log/cloudlibs/ makes sense (seems like a ~duplicate), but 
/var/log/cloud/aws/verifyDeploymentCompletion.js should be named /var/log/cloud/aws/verifyDeploymentCompletion.log

## Template
f5-aws-cloudformation/supported/autoscale/ltm/via-lb/1nic/existing-stack/bigiq/
v5.7.0

## Severity Level
Severity: 5

**Comment by andreykashcheev** [comment]
Thanks for reporting this! 
This issue is tracked internally by ESECLDTPLT-2154

As temp workaround, the log filename can be updated here: 
https://github.com/F5Networks/f5-aws-cloudformation/blob/master/supported/autoscale/waf/via-lb/1nic/existing-stack/bigiq/f5-bigiq-autoscale-bigip-waf.template#L1462

**Comment by andreykashcheev** [comment]
We just have published new templates v5.7.1. which includes the change intended to address this issue. 

Let me know if you have any questions/concerns
