### ISSUE TITLE
BYOL OneBootLocation image types are excluded from Failover templates

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-aws-cloudformation#125]
## Do you already have an issue opened with F5 support?
No

## Description
BYOL failover templates do not have `AllOneBootLocation` and `LTMOneBootLocation` listed under `AllowedValues` for the `imageName` variable.

The corresponding standalone templates do have these images listed. If there are reasons why OneBootLocation must not be used in the case of Failover implementations, they should be documented.

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/failover/across-net/via-api/3nic/existing-stack/byol
and other Failover BYOL templates

## Severity Level
4

**Comment by shyawnkarim** [comment]
The failover templates do not include a single slot option since they are used for infrastructure and should be upgradable in place, however, our [documentation](https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported) says that single slot is an option.

I've filed a documentation bug, internal ID ESECLDTPLT-2310, to get our documentation corrected.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
