### ISSUE TITLE
AMI ids are outdated on f5-existing-stack-byol-2nic-bigip  template

### ISSUE THREAD

**Issue by forestjohnsonpeoplenet** [F5Networks/f5-aws-cloudformation#13]
## Description
Describe the problem you're having or the enhancement you'd like to request.

The AMI ids listed on https://github.com/F5Networks/f5-aws-cloudformation/blob/master/supported/standalone/2nic/f5-existing-stack-byol-2nic-bigip.template seem to have been discontinued. We were unable to launch this stack until we manually updated the ami ID for the ami we are using (we entered an AMI id found on the AWS marketplace for the BYOL image we were trying to use).

## Template
For bugs, enter the template with which you are experiencing issues below.

https://github.com/F5Networks/f5-aws-cloudformation/blob/master/supported/standalone/2nic/f5-existing-stack-byol-2nic-bigip.template

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity:  5

**Comment by puppetx** [comment]
This is true of the hourly template also.

**Comment by NojanMoshiri** [comment]
Sorry about the trouble here, those AMI images were deprecated for new users, our template updates did not happen in time.  We'll improve the process going forward. We will have the templates fixed in a new release coming out tomorrow. 

In the meantime manually updating the AMI IDs is the correct workaround.
