### ISSUE TITLE
Config sync fails when VPC is made up of three IPv4 CIDRs.

### ISSUE THREAD

**Issue by tmarfil** [F5Networks/f5-aws-cloudformation#156]
To replicate the issue:

Use this template (v5.12.0):
https://github.com/F5Networks/f5-aws-cloudformation/tree/main/supported/failover/across-net/via-api/3nic/existing-stack/byol

In us-east-1 region.

***BROKEN***
============

If a VPC is made up of _three_ IPv4 CIDRs:

- 10.21.97.64/26
- 10.21.97.128/26
- 10.21.97.192/26

Subnets
-------
- 10.21.97.64/28 - F5-MGMT-AZ1 - us-east-1a
- 10.21.97.80/28 - F5-MGMT-AZ2 - us-east-1b
- 10.21.97.128/28 - F5-Internal-AZ1 - us-east-1a
- 10.21.97.144/28 - F5-Internal-AZ2 - us-east-1b
- 10.21.97.192/28 - F5-External-AZ1 - us-east-1a
- 10.21.97.208/28 - F5-External-AZ2- us-east-1b

Cloudformation completes but config sync fails. Consistently the same result:
bigip1:
admin@(ip-10-21-97-70)(cfg-sync Disconnected)(Active)(/Common)(tmos)#
bigip2:
admin@(ip-10-21-97-89)(cfg-sync Disconnected (Trust Domain Only))(Active)(/Common)(tmos)# 

***WORKS***
===========

However, if you re-create the VPC with a single IPv4 CIDR:
- 10.21.97.0/24

Same subnets
------------
- 10.21.97.64/28 - F5-MGMT-AZ1 - us-east-1a
- 10.21.97.80/28 - F5-MGMT-AZ2 - us-east-1b
- 10.21.97.128/28 - F5-Internal-AZ1 - us-east-1a
- 10.21.97.144/28 - F5-Internal-AZ2 - us-east-1b
- 10.21.97.192/28 - F5-External-AZ1 - us-east-1a
- 10.21.97.208/28 - F5-External-AZ2- us-east-1b

No problems.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking it internally with ID ESECLDTPLT-2729.

**Comment by mikeoleary** [comment]
I have replicated this issue and can provide some info (@tmarfil and I are working with the same customer).

It appears our startup script in our CFT expects that the VPC in which BIG-IP is deployed has only one CIDR block. When it creates a route called "int-rt" in the LOCAL_ONLY partition on each device, it creates only 1 route entry. Even when there are multiple CIDR blocks in a VPC, only a single route is created for the first CIDR block, routing only the first CIDR block via the internal interfaces. 

If the internal interfaces are in subnets from one of these additional CIDR blocks, and configsync and failover are configured to use Internal Self IPs (as default), then configsync and failover traffic will not route via internal interfaces because the required routes are not present.

Simply adding an internal route for all additional CIDR blocks of the VPC will fix the problem. This can be done manually after deployment, but would be nice if it was handled via the CFT. 

In our case we have an across-net deployment but I think this would be an issue for same-net deployments also.

**Comment by shyawnkarim** [comment]
This issue was resolved with [Release 5.13.0](https://github.com/F5Networks/f5-aws-cloudformation/releases/tag/v5.13.0).
