### ISSUE TITLE
The script can not run in AWS beijing region

### ISSUE THREAD

**Issue by louisleo234** [F5Networks/f5-aws-cloudformation#40]
as below screenshot, it can not be ran in AWS beijing region. could you please double check if there is some thing wrong?
f5-aws-cloudformation/supported/cluster/2nic/across-az-ha/f5-existing-stack-across-az-cluster-byol-2nic-bigip.template

I would like to deploy F5-WAF HA cross two AZ in AWS CN-BeiJing region, would you please give me a instruction and guide docoument? thanks a lot.

![default](https://user-images.githubusercontent.com/35335152/40232615-1aac5680-5ad2-11e8-8601-59fe5fe84e85.png)

**Comment by kskoh** [comment]
The templates currently do not support the AWS beijing region.  Let me check on some information and get back to you.

**Comment by louisleo234** [comment]
is there any update or feed back?

**Comment by kskoh** [comment]
Hi, currently F5 images are not readily available on the AWS marketplace due to regulations.  One needs to build an AMI from F5 download site and upload to your AWS account.  Our F5 China team has done this before with some of the customers in China.  Would you be interested in an opportunity to have a conversation and obtain more details from them ?  I can have them get in touch with you.

**Comment by shyawnkarim** [comment]
Closing. Internal issue ESECLDTPLT-1535 has completed and it has added support for the cn-north-1 region to the following templates:

14.1.2 and 15.0.1 BIG-IP releases

AWS Marketplace 1 Boot Location - (BYOL)
 - F5 BIG-IP VE – LTM/DNS
 - F5 BIG-IP VE – ALL
AWS Marketplace 2 Boot Locations - (BYOL)
 - F5 BIG-IP VE – LTM/DNS
 - F5 BIG-IP VE – ALL
