### ISSUE TITLE
specifying the private ip address value for Management interface, self-ips and virtual server.

### ISSUE THREAD

**Issue by tomonori71** [F5Networks/f5-aws-cloudformation#81]
## Description
I have an enhancement request as the below.
On Parameters page(Specify stack details) of CloudFormationTemplate for BIG-IP,
I would like to specify the private ip address value for Management interface, self-ips and virtual server.

## Template
BIG-IP VE's templates
https://github.com/F5Networks/f5-aws-cloudformation/blob/master/template-index.md

**Comment by shyawnkarim** [comment]
Thanks for taking the time to reach out to us with an enhancement request. 

To help us better understand this request, would you mind telling us about your use case and why being able to specify private IPs for these would be important?

**Comment by tomonori71** [comment]
Thank you for comment.

Because, Many Japanese Enterprise company's NetOps want to decide the value of private ip addresses for the nodes on VPC as same as the on-premises.

I think it is OK that Specifying the private ip addresses function is optional function , however it is necessary for those company's NetOps.

**Comment by shyawnkarim** [comment]
This type of functionality exists today. In order to make changes, to what shows up on the "Specify stack details" page, you'll need to edit the template.

Find the "AWS::CloudFormation::Interface" section of the template and make your changes. For example:

 "Metadata": {
  "AWS::CloudFormation::Interface": {
   "ParameterGroups": [
    {
     "Label": {
      "default": "NETWORKING CONFIGURATION"
     },
     "Parameters": [
      "Vpc",
      "managementSubnetAz1",
      "managementSubnetAz2",
      "subnet1Az1",
      "subnet1Az2",
      "subnet2Az1",
      "subnet2Az2",
      "availabilityZone1",
      "availabilityZone2",
      "numberOfAdditionalNics",
      "additionalNicLocation",
      "provisionPublicIP"
     ]
    },

AWS has documentation on ParameterGroups to help with this as well:
[](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-interface.html)

**Comment by tomonori71** [comment]
Thank you. I see.

I am going to close this issue.
