### ISSUE TITLE
Multiple Target Groups support

### ISSUE THREAD

**Issue by harrykleinb** [F5Networks/f5-aws-cloudformation#91]
## Description
I have a use case where the NLB must use two Target Groups (TG1 and TG2).
TG1 is for receiving TCP/80 trafic from NLB.
TG2 is for receiving TCP/443 trafic from NLB.

The use case is:
Clients must be able to send a request on port 80, then BIGIP must be able to receive the request and redirects the client (HTTP Redirect) to port 443.

Problem:
Regarding the parameter bigipNetworkLoadBalancerTargetGroupsArns: 
The documentation does not state HOW to enter multiple ARNs. It just says to enter the target group(s) (notice the parenthesis+S) indicating that more than one group is allowed.

Can you fix the documentation and explain how to setup multiple Target Groups and whether there is a maximum number too?

I've tried to enter my two ARNs by using different patterns but each time the CFT deployment fails with the error:
Logical ID: BigipAutoscaleGroup: 
Status: CREATE_FAILED
Status Reason: Provided Target Groups may not be valid. Please ensure they exist and try again. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: 380df03c-41f2-11ea-9762-bbb509db6688)

## Template
f5-bigiq-autoscale-bigip-waf-nlb.template release 5.2.1

## Severity Level
Severity: 5

**Comment by JeffGiroux** [comment]
I ran into this issue too. When supplying multiple ARNs for the targetgroup parameter, the CFT will not deploy and instead fails. If you supply only one ARN, the CFT deploys successfully. It seems that the targetgroup variable needs to be an array string instead of normal single-value string. As a result, the 'Ref' function in the script would need to change to Fn, parse each valid ARN, and then place the newly created autoscale group as a member of each targetgroup ARN supplied by user during CFT launch.

For reference...
LTM autoscale version
https://github.com/F5Networks/f5-aws-cloudformation/blob/4e2f7e985817b164db8b6db0b30a5b12fe1e6ef5/experimental/autoscale/ltm/via-nlb/1nic/existing-stack/payg/f5-payg-autoscale-bigip-ltm-nlb.template#L1406
 
The autoscale WAF version has same code logic and will also probably fail if you supply multiple target group ARNs in parameters…
https://github.com/F5Networks/f5-aws-cloudformation/blob/4e2f7e985817b164db8b6db0b30a5b12fe1e6ef5/experimental/autoscale/waf/via-nlb/1nic/existing-stack/payg/f5-payg-autoscale-bigip-waf-nlb.template#L1404
 
According to this, that string should be an array. Not sure if the template is handling it this way or not.
https://docs.aws.amazon.com/sdkforruby/api/Aws/AutoScaling/AutoScalingGroup.html#target_group_arns-instance_method

**Comment by shyawnkarim** [comment]
I've created Jira issue ESECLDTPLT-1820 to add an example of how to enter multiple Target Group ARNs to the documentation. Thanks for your feedback.

**Comment by shyawnkarim** [comment]
Closing. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).

Our V2 templates support customization.
